version: '3.8'

services:
  php:
    environment:
      - APP_ENV=dev
    volumes:
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]

  database:
    ports:
      - "33060:3306"
